import type { CustomThemeDefinition, ThemeConfig } from "./theme.types";

export const activeTheme: ThemeConfig = {
  defaultSelection: "system",
};

export const decorationsEnabled = true;
export const particlesEnabled = true;

export const customThemeDefinitions: CustomThemeDefinition[] = [
  {
    id: "dotmoe",
    label: "dot.moe",
    description: "Muted magenta accent with drifting dot decoration support.",
    enabled: true,
    availability: { type: "always" },
    tokens: {
      background: "247 247 244",
      foreground: "25 29 31",
      surface: "239 240 236",
      surfaceMuted: "232 234 230",
      border: "205 209 204",
      accent: "171 96 155",
      accentMuted: "241 221 237",
      secondaryAccent: "110 128 210",
      selection: "238 211 233",
      gridOpacity: "0.42",
      decorationOpacity: "0.24",
    },
    decoration: { enabled: true, type: "dots", intensity: "low" },
    particles: {
      enabled: true,
      preset: "hearts",
      disableOnMobile: false,
      respectReducedMotion: true,
      options: {
        particles: { color: { value: ["#ab609b", "#c6a0ff"] }, opacity: { value: 0.18 } },
      },
    },
    hero: {
      image: "hero/moe.svg",
      priority: 90,
      availability: {
        type: "gregorian-range",
        timezone: "Asia/Ho_Chi_Minh",
        start: { month: 2, day: 14 },
        end: { month: 2, day: 14 },
      },
    },
    atmosphereCss:
      "body::after{opacity:1;background:radial-gradient(circle at 84% 8%,rgb(255 143 199 / 0.16),transparent 32rem),radial-gradient(circle at 12% 88%,rgb(198 160 255 / 0.12),transparent 30rem);}",
    metadata: { sidebarStatus: "ONLINE", sidebarThemeLabel: "DOT.MOE" },
  },
  {
    id: "monsoon",
    label: "Monsoon Console",
    description: "Rain-dark teal workspace with wet asphalt, cyan status lights, and amber traces.",
    enabled: true,
    availability: {
      type: "gregorian-range",
      timezone: "Asia/Ho_Chi_Minh",
      start: { month: 6, day: 1 },
      end: { month: 9, day: 30 },
    },
    tokens: {
      background: "8 22 25",
      foreground: "224 242 239",
      surface: "13 34 38",
      surfaceMuted: "18 45 50",
      border: "42 83 88",
      accent: "93 207 218",
      accentMuted: "36 86 91",
      secondaryAccent: "231 174 87",
      selection: "24 80 88",
      gridOpacity: "0.22",
      decorationOpacity: "0.14",
    },
    decoration: { enabled: true, type: "dots", intensity: "low" },
    particles: {
      enabled: true,
      preset: "rain",
      disableOnMobile: false,
      respectReducedMotion: true,
    },
    atmosphereCss:
      "body::after{opacity:1;background:radial-gradient(circle at 18% 12%,rgb(93 207 218 / 0.10),transparent 28rem),linear-gradient(115deg,rgb(93 207 218 / 0.08),transparent 34%,rgb(231 174 87 / 0.05));}",
    metadata: {
      sidebarStatus: "RAIN CHECKS PASSING",
      sidebarThemeLabel: "MONSOON CONSOLE",
      seasonLabel: "RAINY RELEASE",
    },
  },
  {
    id: "midautumn",
    label: "Mid-Autumn",
    description: "Lantern gold over moonlit indigo for quiet festival-night reading.",
    enabled: true,
    availability: { type: "manual", enabled: false },
    tokens: {
      background: "18 20 38",
      foreground: "255 243 214",
      surface: "28 31 55",
      surfaceMuted: "38 40 67",
      border: "87 78 105",
      accent: "238 177 76",
      accentMuted: "99 70 44",
      secondaryAccent: "218 92 84",
      selection: "83 63 44",
      gridOpacity: "0.20",
      decorationOpacity: "0.15",
    },
    decoration: { enabled: true, type: "dots", intensity: "low" },
    particles: {
      enabled: true,
      preset: "fireflies",
      disableOnMobile: false,
      respectReducedMotion: true,
      options: {
        particles: {
          number: { value: 38 },
          color: { value: ["#ffd57a", "#eeb14c", "#da5c54"] },
          opacity: { value: 0.34 },
          size: { value: { min: 1.4, max: 3.2 } },
          move: { enable: true, speed: 0.32, direction: "none" },
        },
      },
    },
    hero: {
      image: "hero/midautumn.svg",
      priority: 40,
    },
    metadata: {
      sidebarStatus: "MOONLIGHT BUILD",
      sidebarThemeLabel: "MID-AUTUMN",
      seasonLabel: "LANTERN RELEASE",
    },
  },
  {
    id: "lunar-new-year",
    label: "Lunar New Year",
    description: "Refined crimson, gold, jade, and warm paper for the new-year release window.",
    enabled: true,
    availability: { type: "manual", enabled: false },
    tokens: {
      background: "27 17 18",
      foreground: "255 247 232",
      surface: "41 23 25",
      surfaceMuted: "55 31 31",
      border: "92 54 48",
      accent: "223 75 63",
      accentMuted: "217 170 89",
      secondaryAccent: "242 200 112",
      selection: "97 39 37",
      gridOpacity: "0.22",
      decorationOpacity: "0.18",
    },
    decoration: { enabled: true, type: "blossoms", intensity: "low" },
    particles: {
      enabled: true,
      preset: "apricot-blossoms",
      disableOnMobile: false,
      respectReducedMotion: true,
    },
    hero: { image: "hero/lunar-new-year.svg", priority: 80 },
    metadata: {
      sidebarStatus: "LUCKY DEPLOYMENT",
      sidebarThemeLabel: "LUNAR NEW YEAR",
      seasonLabel: "SPRING RELEASE",
    },
  },
  {
    id: "aurora",
    label: "Aurora Field",
    description: "Polar navy with aurora green, violet glow, and ice-white prose contrast.",
    enabled: true,
    availability: {
      type: "gregorian-range",
      timezone: "Asia/Ho_Chi_Minh",
      start: { month: 12, day: 1 },
      end: { month: 1, day: 31 },
    },
    tokens: {
      background: "7 14 30",
      foreground: "232 246 255",
      surface: "12 24 46",
      surfaceMuted: "17 34 59",
      border: "38 72 96",
      accent: "111 232 184",
      accentMuted: "30 86 74",
      secondaryAccent: "164 133 255",
      selection: "25 79 89",
      gridOpacity: "0.22",
      decorationOpacity: "0.16",
    },
    decoration: { enabled: true, type: "dots", intensity: "low" },
    particles: {
      enabled: true,
      preset: "snow",
      disableOnMobile: false,
      respectReducedMotion: true,
    },
    hero: {
      image: "hero/aurora.svg",
      priority: 70,
      availability: {
        type: "gregorian-range",
        timezone: "Asia/Ho_Chi_Minh",
        start: { month: 12, day: 25 },
        end: { month: 1, day: 5 },
      },
    },
    atmosphereCss:
      "body::after{opacity:1;background:linear-gradient(112deg,transparent 8%,rgb(111 232 184 / 0.16) 28%,rgb(164 133 255 / 0.12) 46%,transparent 68%),radial-gradient(circle at 80% 18%,rgb(164 133 255 / 0.12),transparent 28rem);}",
    metadata: {
      sidebarStatus: "AURORA ONLINE",
      sidebarThemeLabel: "AURORA FIELD",
      seasonLabel: "POLAR RELEASE",
    },
  },
  {
    id: "cherry-blossom",
    label: "Cherry Blossom",
    description: "Soft spring pink, plum ink, ivory surfaces, and muted green accents.",
    enabled: true,
    availability: {
      type: "gregorian-range",
      timezone: "Asia/Ho_Chi_Minh",
      start: { month: 3, day: 1 },
      end: { month: 4, day: 30 },
    },
    tokens: {
      background: "252 244 248",
      foreground: "38 29 38",
      surface: "246 234 241",
      surfaceMuted: "239 224 234",
      border: "214 185 204",
      accent: "190 93 145",
      accentMuted: "243 211 229",
      secondaryAccent: "104 145 116",
      selection: "238 201 225",
      gridOpacity: "0.34",
      decorationOpacity: "0.18",
    },
    decoration: { enabled: true, type: "blossoms", intensity: "low" },
    particles: {
      enabled: true,
      preset: "cherry-leaves",
      disableOnMobile: false,
      respectReducedMotion: true,
    },
    hero: {
      image: "hero/cherry-blossom.svg",
      priority: 60,
      availability: {
        type: "gregorian-range",
        timezone: "Asia/Ho_Chi_Minh",
        start: { month: 3, day: 15 },
        end: { month: 4, day: 15 },
      },
    },
    metadata: {
      sidebarStatus: "SPRING PREVIEW",
      sidebarThemeLabel: "CHERRY BLOSSOM",
      seasonLabel: "SPRING RELEASE",
    },
  },
  {
    id: "halloween",
    label: "Halloween Build",
    description: "Muted pumpkin, violet fog, and charcoal surfaces for an October deploy.",
    enabled: true,
    availability: {
      type: "gregorian-range",
      timezone: "Asia/Ho_Chi_Minh",
      start: { month: 10, day: 24 },
      end: { month: 10, day: 31 },
    },
    tokens: {
      background: "17 15 21",
      foreground: "242 235 223",
      surface: "29 24 35",
      surfaceMuted: "40 32 47",
      border: "78 62 84",
      accent: "222 128 58",
      accentMuted: "88 53 34",
      secondaryAccent: "167 117 224",
      selection: "88 54 37",
      gridOpacity: "0.21",
      decorationOpacity: "0.14",
    },
    decoration: { enabled: true, type: "dots", intensity: "low" },
    particles: {
      enabled: true,
      preset: "fireflies",
      disableOnMobile: false,
      respectReducedMotion: true,
      options: {
        particles: {
          number: { value: 24 },
          color: { value: ["#de803a", "#a775e0", "#f2ebdf"] },
          opacity: { value: 0.18 },
          size: { value: { min: 1, max: 2.4 } },
          move: { enable: true, speed: 0.18, direction: "none" },
        },
      },
    },
    hero: {
      image: "hero/halloween.svg",
      priority: 75,
      availability: {
        type: "gregorian-range",
        timezone: "Asia/Ho_Chi_Minh",
        start: { month: 10, day: 24 },
        end: { month: 10, day: 31 },
      },
    },
    atmosphereCss:
      "body::after{opacity:1;background:radial-gradient(circle at 12% 88%,rgb(222 128 58 / 0.14),transparent 24rem),radial-gradient(circle at 82% 16%,rgb(167 117 224 / 0.13),transparent 26rem),linear-gradient(180deg,transparent 0%,rgb(0 0 0 / 0.16) 100%);}",
    metadata: {
      sidebarStatus: "OCTOBER BUILD",
      sidebarThemeLabel: "HALLOWEEN",
      seasonLabel: "FALL RELEASE",
    },
  },
  {
    id: "terminal-green",
    label: "Terminal Green",
    description:
      "Near-black console theme with phosphor green text and restrained scanline energy.",
    enabled: true,
    availability: { type: "always" },
    tokens: {
      background: "6 12 9",
      foreground: "210 245 218",
      surface: "10 20 15",
      surfaceMuted: "14 30 21",
      border: "39 79 52",
      accent: "112 238 138",
      accentMuted: "31 80 44",
      secondaryAccent: "154 214 132",
      selection: "24 79 45",
      gridOpacity: "0.20",
      decorationOpacity: "0.10",
    },
    decoration: { enabled: true, type: "dots", intensity: "low" },
    metadata: {
      sidebarStatus: "TTY READY",
      sidebarThemeLabel: "TERMINAL GREEN",
    },
  },
  {
    id: "midnight-blueprint",
    label: "Midnight Blueprint",
    description: "Navy blueprint workspace with cyan lines, steel borders, and off-white text.",
    enabled: true,
    availability: { type: "always" },
    tokens: {
      background: "8 16 31",
      foreground: "230 239 247",
      surface: "13 27 48",
      surfaceMuted: "18 38 63",
      border: "54 82 112",
      accent: "97 203 232",
      accentMuted: "32 79 103",
      secondaryAccent: "139 170 202",
      selection: "31 81 107",
      gridOpacity: "0.30",
      decorationOpacity: "0.12",
    },
    decoration: { enabled: true, type: "dots", intensity: "low" },
    metadata: {
      sidebarStatus: "BLUEPRINT SYNCED",
      sidebarThemeLabel: "MIDNIGHT BLUEPRINT",
    },
  },
  {
    id: "winter",
    label: "Winter Deploy",
    description: "Quiet midnight deployment theme with icy blue, pine, and soft red accents.",
    enabled: true,
    availability: {
      type: "gregorian-range",
      timezone: "Asia/Ho_Chi_Minh",
      start: { month: 12, day: 1 },
      end: { month: 1, day: 7 },
    },
    tokens: {
      background: "9 18 28",
      foreground: "238 247 255",
      surface: "16 31 45",
      surfaceMuted: "21 40 57",
      border: "41 68 91",
      accent: "143 211 255",
      accentMuted: "155 215 189",
      secondaryAccent: "233 132 132",
      selection: "29 71 94",
      gridOpacity: "0.24",
      decorationOpacity: "0.16",
    },
    decoration: { enabled: true, type: "snow", intensity: "low" },
    particles: {
      enabled: true,
      preset: "snow",
      disableOnMobile: false,
      respectReducedMotion: true,
    },
    hero: { image: "hero/winter.svg", priority: 50 },
    metadata: {
      sidebarStatus: "ALL SYSTEMS COZY",
      sidebarThemeLabel: "WINTER DEPLOY",
      seasonLabel: "YEAR-END RELEASE",
    },
  },
];

export const enabledCustomThemes = customThemeDefinitions.filter((theme) => theme.enabled);
